# Docker Compose configuration
version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key
      - MONGO_URI=mongodb://mongo:27017/video_streaming
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=your-aws-access-key-id
      - AWS_SECRET_ACCESS_KEY=your-aws-secret-access-key
      - AWS_BUCKET_NAME=your-s3-bucket-name
      - AWS_REGION=your-aws-region
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask

volumes:
  mongo-data:
